### ISSUE TITLE
Import errors, and can't find _readTTTRRecords_build.py to compile dynamic library

### ISSUE THREAD

**Issue by LennyHirsch** [QuantumPhotonicsLab/readPTU#3]
I am attempting to run on Python 2.7.10 on MacOS.
When trying to import readPTU module, the following error is thrown:

```
from _readTTTRRecords_HHT2_HH2 import ffi, lib
    ImportError: No module named _readTTTRRecords_HHT2_HH2
```

The error gets thrown when trying to run line 33 of the `readPTU.py` file.

Following this I wanted to try to compile the dynamic library to see if this fixes this issue, but I cannot find the `_readTTTRRecords_build.py` file referred to in the readme.

Am I doing something wrong, or is the `_readTTTRRecords_build.py` file missing/no longer available?

Below is the code that I am trying to run:

```
import readPTU as ptu

ptuFile = ptu.PTUfile("HOM-T3-0.80.ptu")
ptuFile.print_header()
```

**Comment by binSmile** [comment]
I'm also have this problem. On linux and on windows 10
 @LennyHirsch, Do you solved it?

**Comment by LennyHirsch** [comment]
@binSmile no, no solve yet. We had some luck using Matlab demo code provided with the HydraHarp, but no luck with this python code unfortunately :(

**Comment by binSmile** [comment]
thanks for your reply!

сб, 20 июн. 2020 г. в 13:26, LennyHirsch <notifications@github.com>:

**Comment by edizh** [comment]
Same issue here on Win10.

**Comment by raphaelproux** [comment]
Hi everyone, 
I am not supporting this code so much anymore but I noticed several of you are having this issue... How are you installing the package exactly? I agree the installation instructions are not clear but what you should be doing is going to wherever you cloned the repository and do `pip install .`

**Comment by GCBallesteros** [comment]
Hi everyone,
As @raphaelproux  I'm not maintaining this code anymore. You are right in that the README is out of sync with the library. `_readTTTRRecords_build.py` is not there anymore. Instead the setup.py file is responsible for orchestrating the compilation of the C components. `_readTTTRRecords_HHT2_HH2` is one of the libraries generated during compilation. The error that you are seeing indicates that compilation either didn't take place or if it did, the library wasn't left in a place where Python can find it.

I will prepare better instructions and come back with more details. I will also ask somebody currently in the lab to update the README as soon as I can.

EDIT: I have just verified that the following instructions work on MacOS with Python3.7 under the assumption that you have a C compiler available.
1. `git clone https://github.com/QuantumPhotonicsLab/readPTU`
2. navigate to readPTU
3. Edit readPTU.py lines 33 to 36 so that the import statements start with a `.`. That is,
`from _readTTTRRecords_HHT2_HH2 import ffi, lib -> from ._readTTTRRecords_HHT2_HH2 import ffi, lib`
4. python3.7 setup.py install

When running step 4 you should see the output from the compilation steps. You can then verify that everything worked by opening a Python REPL and trying to import readPTU.

Please let me know if the above steps were of any help.

**Comment by edizh** [comment]
The instructions worked for me on Win10 with Python 3.7.4. However, this only works for me in the installation folder and not if I want to import the package outside of that folder. To make it work outside of the installation folder I had to copy the files

`_readTTTRRecords_HHT2_HH1.cp37-win_amd64.pyd`
`_readTTTRRecords_HHT2_HH2.cp37-win_amd64.pyd`
`_readTTTRRecords_PHT2.cp37-win_amd64.pyd`

into the installation folder of my packages. In my case this was:

`C:\Users\<MyUser>\AppData\Local\Continuum\anaconda3\Lib\site-packages\readPTU`

I am not sure why the files are not present in that folder. Maybe one of the contributers has a smoother solution for that?

**Comment by lostiles13** [comment]
Hi! Has anyone else figured out a solution to this problem? I have tried all the above steps and have not found something that works.  Or a new addition of the code? Thank you!

**Comment by Rlwilmington** [comment]
Exact same issue as @LennyHirsch (python 3.7, Win10-64bit), but @lostiles13 I did find a workaround if you are just trying to run the code:

First, I was never able to call the readPTU module successfully, due to the "no module readTTTRRecords_HHT2_HH2 found issue. I verified those modules did exist, and they are present as .pyd files in the build location. I even tried manually moving them to the python site-packages as @EdKaHe also tried, though that also still resulting in the "modules not found error".

Ultimately, what did work for me is the following simple (albeit un-elegant) solution: I simply wrote the "main script" I intended to execute in the readPTU.py file itself. This occurred to me after I realized that in at least the current distribution, that is sort of already how the code is implemented. If you scroll to the end of the file, you'll find that there is already an example filename and set of options set, and if you run the readPTU.py file (after building, and the one that shows up with the .pyd files in the same folder) as a script in IDLE, and change the dummy filename to a real PTU file, you can actually get the code to run. The code efficiency timer still threw an error so I just deleted those lines (again, apologies for my bootleg methodology), but after those steps, I was able to get the file header info to appear, and even plots to generate. I then just modified the window and resolution parameters to what I needed, and now I can complete my analysis.

Unsure exactly why running the script as a whole doesn't throw the readTTTRRecords_HHT2_HH2 not found error, but this allowed me to at least practically use the code.

**Comment by raphaelproux** [comment]
Following the pull request #4  of @Jfeatherstone and following the new install instructions, the library compiles at install without problems.
